### ISSUE TITLE
Cannot import IlovePdfJS in browser

### ISSUE THREAD

**Issue by stonedMoose** [ilovepdf/ilovepdf-js#11]
On a VueJS 2 project, I try to compress a pdf file before sending it to the server, but I cannot find a way to import without getting an error.

Whenever I try to import it I got the error:
> TypeError: Object prototype may only be an Object or null.

I tried to import it the traditionnal way, using:
```ts
import ILovePDFApi from '@ilovepdf/ilovepdf-js';
import ILovePDFFile from "@ilovepdf/ilovepdf-js/ILovePDFFile";
```

but it prevented my vue component to be loaded.

So I try to import it another way:
```ts
const iLovePdf = await import('@ilovepdf/ilovepdf-js').then((res) => {
      console.log(res);
      return res.default;
});
const ILoveFile = await import('@ilovepdf/ilovepdf-js/ILovePDFFile').then((res) => {
      console.log(res);
      return res.default;
});
```

this time my component is mounted, but when I call the code that does the asynchronous import I got the same error.

I'm using node `v18.12.0` along with npm `8.19.2`.

Any idea on how to make the library works in my browser ? what I could be doing wrong ?

**Comment by stonedMoose** [comment]
I tried using the v0.2.0

**Comment by diego-ilovepdf** [comment]
Hi @stonedMoose !

Probably something happens on your side, try to look your config files or where it is imported. I tested a Vue3 version, however [it seems that also works](https://codesandbox.io/p/sandbox/vue-2-playground-forked-5y77tr?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqgqnajp00063j6gije5mi88%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqgqnajp00023j6g4luedzu6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqgqnajp00033j6gwodtlfro%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqgqnajp00053j6gtr6641uw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqgqnajp00023j6g4luedzu6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqgqnajo00013j6g4fmpmgqu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Ffavicon.ico%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqgqnajp00023j6g4luedzu6%2522%252C%2522activeTabId%2522%253A%2522clqgqnajo00013j6g4fmpmgqu%2522%257D%252C%2522clqgqnajp00053j6gtr6641uw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqgqnajp00043j6gdechyg7j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqgqnajp00053j6gtr6641uw%2522%252C%2522activeTabId%2522%253A%2522clqgqnajp00043j6gdechyg7j%2522%257D%252C%2522clqgqnajp00033j6gwodtlfro%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqgqnajp00033j6gwodtlfro%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A28.350785340314133%257D) with Vue2.
