### ISSUE TITLE
Can I somehow get how many credits I have left on ilovepdf api?

### ISSUE THREAD

**Issue by AbelSapa** [ilovepdf/ilovepdf-js#12]
I have a small code to use the api, but i would like to redirect the petitions if we dont have more credits of the api. I'm using it to compres pdfs, and it would be good, that if i cannot compres any more files, simply dont compres it.

`  private async getClient() {
    const iLovePDFApi: any = await import('@ilovepdf/ilovepdf-nodejs');
    return new iLovePDFApi(this.API_KEY, this.API_SECRET);
  }

  public async compress(file: Buffer): Promise<Buffer> {
    const ILovePDFFile: any = await import(
      '@ilovepdf/ilovepdf-nodejs/ILovePDFFile'
    );
    const client = await this.getClient();  //Get how many credits from client
    const task = client.newTask('compress');
    await task.start();
    const dirName = Date.now().toString();
    const filePath = await this.saveTmpFile(dirName, file);
    const uploadedFile = new ILovePDFFile(filePath);
    await task.addFile(uploadedFile);
    await task.process();
    const compressed = await task.download();
    await this.removeTmpFile(dirName);
    return Buffer.from(compressed);
  }`

**Comment by diego-ilovepdf** [comment]
Hi again @AbelSapa !

Last library version allows you to know the remaining files. You have an example at the end of the README.md at https://github.com/ilovepdf/ilovepdf-js

Nice day.
